# Generated by Django 4.1.7 on 2023-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
            ],
        ),
    ]
